<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-danilbalistero/blob/main/TarefaPratica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fáceis
### 1. Vetor de zeros
**Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.**

In [154]:
import numpy as np

a1D = np.zeros(10)
print(a1D)
print(a1D.dtype)
print(a1D.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


### 2. Vetor de uns  _(fácil)_

**Crie um array 1D com 10 uns e transforme-o em float64.**

In [155]:
a1D = np.ones(10)
print(a1D)
print(a1D.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64



### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [156]:
a1D = np.arange(10)
print(a1D)

[0 1 2 3 4 5 6 7 8 9]



### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [157]:
a2D = np.arange(9).reshape(3, 3)
print(a2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 5. Índices não zero  _(fácil)_

Dado o vetor `v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

In [158]:
v = np.array([1,2,0,0,4,0])
np.nonzero(v)

(array([0, 1, 4]),)

### 6. Linspace  _(fácil)_

Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].

In [159]:
a = np.linspace(0,1, num=12)
print(a)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


## 7. Identidade 5×5  _(fácil)_

Crie uma matriz identidade de ordem 5.

In [160]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [161]:
rng = np.random.default_rng(42)
a = rng.random((3,3,3))
print(a)

[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]


### 8. Aleatórios 3×3×3  _(fácil)_

Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.

In [162]:
rng = np.random.default_rng(42)

array_aleatorio = rng.random((3, 3, 3))

print("Array 3x3x3 com valores aleatórios:")
print(array_aleatorio)

Array 3x3x3 com valores aleatórios:
[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]



### 9. Min/Max  _(fácil)_

Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.

In [163]:
rng = np.random.default_rng(42)

matriz = rng.random((10, 10))

valor_min = matriz.min()
valor_max = matriz.max()

print("Matriz 10x10 gerada (apenas as 5 primeiras linhas para visualização):")
print(matriz[:5, :])
print("\n" + "="*40 + "\n")
print(f"Valor Mínimo na matriz: {valor_min}")
print(f"Valor Máximo na matriz: {valor_max}")

Matriz 10x10 gerada (apenas as 5 primeiras linhas para visualização):
[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
  0.7611397  0.78606431 0.12811363 0.45038594]
 [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142  0.22723872
  0.55458479 0.06381726 0.82763117 0.6316644 ]
 [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835  0.19463871
  0.466721   0.04380377 0.15428949 0.68304895]
 [0.74476216 0.96750973 0.32582536 0.37045971 0.46955581 0.18947136
  0.12992151 0.47570493 0.22690935 0.66981399]
 [0.43715192 0.8326782  0.7002651  0.31236664 0.8322598  0.80476436
  0.38747838 0.2883281  0.6824955  0.13975248]]


Valor Mínimo na matriz: 0.007362269751005512
Valor Máximo na matriz: 0.9756223516367559



### 10. Padronização 1D  _(fácil)_

Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

In [164]:
x = np.array([1, 2, 3, 4, 5])

x_float = x.astype(np.float64)

media = np.mean(x_float)
desvio_padrao = np.std(x_float)
x_normalizado = (x_float - media) / desvio_padrao

print("Array original:", x)
print("Array float:", x_float)
print("Array normalizado (média 0, desvio 1):", x_normalizado)

Array original: [1 2 3 4 5]
Array float: [1. 2. 3. 4. 5.]
Array normalizado (média 0, desvio 1): [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]



### 11. Conversão de tipos  _(fácil)_

Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.

In [165]:
array_inicial = np.array([1, 2, 3])
print(f"Array Original: {array_inicial}")
print(f"Dtype Original: {array_inicial.dtype}")
print("-" * 35)

array_float32 = array_inicial.astype(np.float32)
print(f"Array convertido para float32: {array_float32}")
print(f"Novo Dtype: {array_float32.dtype}")
print("-" * 35)

array_int64 = array_float32.astype(np.int64)
print(f"Array convertido para int64: {array_int64}")
print(f"Dtype Final: {array_int64.dtype}")

Array Original: [1 2 3]
Dtype Original: int64
-----------------------------------
Array convertido para float32: [1. 2. 3.]
Novo Dtype: float32
-----------------------------------
Array convertido para int64: [1 2 3]
Dtype Final: int64



### 12. Clipping  _(fácil)_

Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).

In [166]:
a = np.array([2, 5, 7, 1, 9])

a_limitado = np.clip(a, 0, 5)

print("Array Original: {a}")
print("Array Limitado ao intervalo [0, 5]: {a_limitado}")

Array Original: {a}
Array Limitado ao intervalo [0, 5]: {a_limitado}


### 13. Inversão  _(fácil)_

Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).


In [167]:
vetor_original = np.arange(10)

vetor_invertido = np.flip(vetor_original)

print(f"Vetor Original:  {vetor_original}")
print(f"Vetor Invertido: {vetor_invertido}")

Vetor Original:  [0 1 2 3 4 5 6 7 8 9]
Vetor Invertido: [9 8 7 6 5 4 3 2 1 0]



### 14. Empilhamento  _(fácil)_

Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.

In [168]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado_vertical = np.vstack((a, b))
print("Resultado Vertical (um em cima do outro):")
print(resultado_vertical)

resultado_horizontal = np.hstack((a, b))
print("Resultado Horizontal (um ao lado do outro):")
print(resultado_horizontal)

Resultado Vertical (um em cima do outro):
[[1 2 3]
 [4 5 6]]
Resultado Horizontal (um ao lado do outro):
[1 2 3 4 5 6]



### 15. Diagonal  _(fácil)_

Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.


In [169]:
matriz = np.diag([5, 5, 5, 5])

print(matriz)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


### 16. Somas por eixo  _(fácil)_

Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.

In [170]:
A = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

print("Matriz A:")
print(A)
print("-" * 25)

soma_linhas = A.sum(axis=1)
print(f"Soma das linhas: {soma_linhas}")

soma_colunas = A.sum(axis=0)
print(f"Soma das colunas: {soma_colunas}")

Matriz A:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------------------
Soma das linhas: [ 6 22 38]
Soma das colunas: [12 15 18 21]



### 17. Frequências inteiras  _(fácil)_

Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).

In [171]:
rng = np.random.default_rng(42)

numeros = rng.integers(0, 10, size=100)

contagem = np.bincount(numeros, minlength=10)

print(f"Números aleatórios (20 primeiros): {numeros[:20]}...")
print(f"\nContagem de cada número (de 0 a 9):")
print(contagem)

Números aleatórios (20 primeiros): [0 7 6 4 4 8 0 6 2 0 5 9 7 7 7 7 5 1 8 4]...

Contagem de cada número (de 0 a 9):
[ 9  9  6  9 15  7 11 15 12  7]



### 18. Slicing com passo  _(fácil)_

Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.

In [172]:
v = np.arange(20)
print(f"Vetor Original: {v}")

resultado = v[1::3]

print(f"Resultado     : {resultado}")

Vetor Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Resultado     : [ 1  4  7 10 13 16 19]



### 19. Máscara booleana  _(fácil)_

Crie uma máscara para números pares de `0…19` e use-a para filtrar o vetor.


In [173]:
v = np.arange(20)
print(f"Vetor Original: {v}")

mascara_pares = (v % 2 == 0)
print(f"Máscara (True para pares): {mascara_pares}")

numeros_pares = v[mascara_pares]

print(f"Números Pares (filtrados): {numeros_pares}")

Vetor Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Máscara (True para pares): [ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]
Números Pares (filtrados): [ 0  2  4  6  8 10 12 14 16 18]



### 20. Lista de listas → array  _(fácil)_

Converta `[[1,2,3],[4,5,6]]` em `ndarray`, verifique `shape` e `dtype`.

In [174]:
lista_python = [[1, 2, 3], [4, 5, 6]]

meu_array = np.array(lista_python)

print(f"O array NumPy (ndarray):")
print(meu_array)

print("\n--- Informações do Array ---")
print(f"Shape: {meu_array.shape}")
print(f"Dtype: {meu_array.dtype}")

O array NumPy (ndarray):
[[1 2 3]
 [4 5 6]]

--- Informações do Array ---
Shape: (2, 3)
Dtype: int64



### 21. Datas básicas  _(fácil)_

Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).

In [175]:
datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')

print("Array de datas:")
print(datas)

Array de datas:
['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07']


### 22. Centralizar colunas  _(fácil)_

Dada `A = np.array([[1.,2.,3.],[4.,5.,6.]])`, subtraia a média de cada coluna.


In [176]:
A = np.array([[1., 2., 3.],
              [4., 5., 6.]])
print(f"Matriz Original (A) shape: {A.shape}")
print(A)

media_colunas = A.mean(axis=0)
print(f"\nMédia de cada coluna: {media_colunas}")
print(f"Shape do vetor de médias: {media_colunas.shape}")

A_centralizado = A - media_colunas

print(f"\nMatriz Centralizada (resultado):")
print(A_centralizado)

print(f"\nNova média das colunas (verificação):")
print(A_centralizado.mean(axis=0))

Matriz Original (A) shape: (2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]

Média de cada coluna: [2.5 3.5 4.5]
Shape do vetor de médias: (3,)

Matriz Centralizada (resultado):
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]

Nova média das colunas (verificação):
[0. 0. 0.]


### 23. Produto elemento-a-elemento vs. escalar  _(fácil)_

Dadas `a=[1,2,3]` e `b=[4,5,6]`, calcule produto elemento a elemento e o produto escalar.


In [177]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"Vetor a: {a}")
print(f"Vetor b: {b}")
print("\n" + "="*45 + "\n")

prod_elemento = a * b

print("--- 1. Produto Elemento a Elemento ---")
print(f"Resultado (a * b): {prod_elemento}")
print("Explicação: [1*4, 2*5, 3*6]")
print("\n" + "="*45 + "\n")

prod_escalar_dot = np.dot(a, b)

prod_escalar_at = a @ b

print("--- 2. Produto Escalar (Dot Product) ---")
print(f"Resultado (np.dot(a, b)): {prod_escalar_dot}")
print(f"Resultado (a @ b):         {prod_escalar_at}")
print("Explicação: (1*4) + (2*5) + (3*6) = 4 + 10 + 18")

Vetor a: [1 2 3]
Vetor b: [4 5 6]


--- 1. Produto Elemento a Elemento ---
Resultado (a * b): [ 4 10 18]
Explicação: [1*4, 2*5, 3*6]


--- 2. Produto Escalar (Dot Product) ---
Resultado (np.dot(a, b)): 32
Resultado (a @ b):         32
Explicação: (1*4) + (2*5) + (3*6) = 4 + 10 + 18


### 24. Troca de colunas  _(fácil)_

Troque as colunas 0 e 2 de `A = np.arange(12).reshape(3,4)` sem copiar (sempre que possível).

In [178]:
A = np.arange(12).reshape(3, 4)
print("Matriz Original (A):")
print(A)

temp = A[:, 0].copy()

A[:, 0] = A[:, 2]

A[:, 2] = temp

print("\nMatriz Modificada (A):")
print(A)

Matriz Original (A):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Matriz Modificada (A):
[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


## Médios (12)

### 25. Flatten vs. ravel  _(médio)_

Mostre a diferença entre `flatten()` (cópia) e `ravel()` (view quando possível). Modifique o resultado de `ravel()` e observe o original.

In [179]:
A_copia = np.array([[1, 2], [3, 4]])
resultado_copia = A_copia.flatten()

resultado_copia[0] = 99

print(f"Resultado (flatten): {resultado_copia}")
print(f"Original (A_copia): {A_copia}")
print("-" * 20)


A_original = np.array([[1, 2], [3, 4]])
resultado_ravel = A_original.ravel()

resultado_ravel[0] = 99

print(f"Resultado (ravel): {resultado_ravel}")
print(f"Original (A_original): {A_original}")

Resultado (flatten): [99  2  3  4]
Original (A_copia): [[1 2]
 [3 4]]
--------------------
Resultado (ravel): [99  2  3  4]
Original (A_original): [[99  2]
 [ 3  4]]


### 26. Tabuleiro 8×8  _(médio)_

Crie uma matriz 8×8 com padrão de tabuleiro (0 e 1 alternados).

In [180]:
tabuleiro = np.zeros((8, 8), dtype=int)

tabuleiro[::2, 1::2] = 1

tabuleiro[1::2, ::2] = 1

print(tabuleiro)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 27. np.where condicional  _(médio)_

Dado `x = np.arange(-5,6)`, substitua negativos por 0 e mantenha não-negativos.

In [181]:
x = np.arange(-5, 6)
print(f"Vetor Original: {x}")

resultado = np.where(x < 0, 0, x)

print("Resultado com np.where:")
print(resultado)

Vetor Original: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Resultado com np.where:
[0 0 0 0 0 0 1 2 3 4 5]


### 28. Precisão de média  _(médio)_

Gere 1_000_000 floats uniformes em [0,1) e compute a média. Compare com o valor teórico 0.5 (erro absoluto).

In [182]:
tamanho_amostra = 1_000_000
dado = 42

rng = np.random.default_rng(dado)
numeros = rng.random(size=tamanho_amostra)

media_calculada = numeros.mean()

media_teorica = 0.5

erro_absoluto = abs(media_calculada - media_teorica)

print(f"Tamanho da amostra: {tamanho_amostra:,}")

print(f"Média calculada: {media_calculada:.8f}")
print(f"Média teórica:    {media_teorica:.8f}")
print(f"Erro absoluto:    {erro_absoluto:.8f}")

Tamanho da amostra: 1,000,000
Média calculada: 0.50002648
Média teórica:    0.50000000
Erro absoluto:    0.00002648


### 29. Produto cartesiano (broadcasting)  _(médio)_

Dado `a=[1,2,3]` e `b=[10,20,30,40]`, gere todas as somas possíveis `a_i + b_j` via broadcasting (matriz 3×4).

In [183]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])

print(f"Vetor 'a' (shape {a.shape}): {a}")
print(f"Vetor 'b' (shape {b.shape}): {b}")

a_coluna = a[:, np.newaxis]

print(f"'a' como coluna (shape {a_coluna.shape}):")
print(a_coluna)

resultado = a_coluna + b

print("Resultado")
print(resultado)

Vetor 'a' (shape (3,)): [1 2 3]
Vetor 'b' (shape (4,)): [10 20 30 40]
'a' como coluna (shape (3, 1)):
[[1]
 [2]
 [3]]
Resultado
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


### 30. Convolução 1D simples  _(médio)_

Implemente uma convolução 1D 'valid' de um sinal `s` por um kernel `k` usando `np.flip` e `np.lib.stride_tricks.sliding_window_view` (sem `np.convolve`).

In [186]:
sinal = np.array([1, 2, 3, 4, 5, 6, 7])
kernel = np.array([10, 20, 30])

kernel_invertido = np.flip(kernel)
print(f"Kernel invertido: {kernel_invertido}")

fatias = sliding_window_view(sinal, window_shape=len(kernel))

print(f"Fatias do sinal (o 'deslizar'):")
print(fatias)
resultado = fatias @ kernel_invertido

print(resultado)

Kernel invertido: [30 20 10]
Fatias do sinal (o 'deslizar'):
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]
[100 160 220 280 340]


### 31. Normalização min–max por coluna  _(médio)_

Dada `A = rng.normal(size=(5,4))`, normalize cada coluna para o intervalo [0,1], tratando colunas constantes.


### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.


In [187]:
rng = np.random.default_rng(42)
A = rng.normal(size=(5, 4))

A[:, 2] = 5.0

print(f"Matriz Original (Coluna 2 é constante):\n{A}\n")

col_min = A.min(axis=0)
col_max = A.max(axis=0)

col_range = col_max - col_min

numerator = A - col_min

A_normalizada = np.where(col_range != 0, numerator / col_range, 0)

print(f"Matriz Normalizada [0, 1]")
print(A_normalizada)

print("Verificação")
print(f"Novo Mínimo por coluna: {A_normalizada.min(axis=0)}")
print(f"Novo Máximo por coluna: {A_normalizada.max(axis=0)}")

Matriz Original (Coluna 2 é constante):
[[ 0.30471708 -1.03998411  5.          0.94056472]
 [-1.95103519 -1.30217951  5.         -0.31624259]
 [-0.01680116 -0.85304393  5.          0.77779194]
 [ 0.0660307   1.12724121  5.         -0.85929246]
 [ 0.36875078 -0.9588826   5.         -0.04992591]]

Matriz Normalizada [0, 1]
[[0.97239672 0.10792507 0.         1.        ]
 [0.         0.         0.         0.30171831]
 [0.83379849 0.18487353 0.         0.9095635 ]
 [0.86950517 1.         0.         0.        ]
 [1.         0.14130813 0.         0.44968376]]
Verificação
Novo Mínimo por coluna: [0. 0. 0. 0.]
Novo Máximo por coluna: [1. 1. 0. 1.]


/tmp/ipython-input-1117866444.py:15: RuntimeWarning: invalid value encountered in divide
  A_normalizada = np.where(col_range != 0, numerator / col_range, 0)


### 32. Ordenar por coluna  _(médio)_

Ordene as linhas de `A = np.array([[3,9],[1,4],[2,5]])` pelo valor crescente da 2ª coluna.

In [188]:
A = np.array([[3, 9],
              [1, 4],
              [2, 5]])
print(f"Matriz Original:\n{A}")

coluna_chave = A[:, 1]
print(f"\nValores da coluna-chave (índice 1): {coluna_chave}")

indices_ordenados = np.argsort(coluna_chave)
print(f"Índices ordenados (resultado do argsort): {indices_ordenados}")

A_ordenado = A[indices_ordenados]

print(f"\nMatriz Ordenada pela 2ª coluna:")
print(A_ordenado)

Matriz Original:
[[3 9]
 [1 4]
 [2 5]]

Valores da coluna-chave (índice 1): [9 4 5]
Índices ordenados (resultado do argsort): [1 2 0]

Matriz Ordenada pela 2ª coluna:
[[1 4]
 [2 5]
 [3 9]]


### 33. Únicos + contagens + primeira ocorrência  _(médio)_

Para `x = [3,1,2,3,2,3,1]`, obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.

In [189]:
x = np.array([3, 1, 2, 3, 2, 3, 1])
print(f"Array Original: {x}")
print("Índices:          [0, 1, 2, 3, 4, 5, 6]")

unicos, indices_primeira, contagens = np.unique(x,
                                                return_index=True,
                                                return_counts=True)

print("\n" + "="*45 + "\n")
print(f"1. Valores Únicos (ordenados):    {unicos}")
print(f"2. Índice da Primeira Ocorrência: {indices_primeira}")
print(f"3. Contagens (quantas vezes):   {contagens}")

print("Explicação dos Resultados")
print(f"Valor {unicos[0]}: Primeira vez no índice {indices_primeira[0]}. Apareceu {contagens[0]} vezes.")
print(f"Valor {unicos[1]}: Primeira vez no índice {indices_primeira[1]}. Apareceu {contagens[1]} vezes.")
print(f"Valor {unicos[2]}: Primeira vez no índice {indices_primeira[2]}. Apareceu {contagens[2]} vezes.")

Array Original: [3 1 2 3 2 3 1]
Índices:          [0, 1, 2, 3, 4, 5, 6]


1. Valores Únicos (ordenados):    [1 2 3]
2. Índice da Primeira Ocorrência: [1 2 0]
3. Contagens (quantas vezes):   [2 2 3]
Explicação dos Resultados
Valor 1: Primeira vez no índice 1. Apareceu 2 vezes.
Valor 2: Primeira vez no índice 2. Apareceu 2 vezes.
Valor 3: Primeira vez no índice 0. Apareceu 3 vezes.


## 34. Matriz de distâncias 2D  _(médio)_

Dada `P` com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos.

In [190]:
rng = np.random.default_rng(42)
N = 5
P = rng.random((N, 2))

print(f"Pontos Originais (P) shape: {P.shape}\n{P}\n")

X = P[:, 0:1]
Y = P[:, 1:2]

deltas_X = X - X.T
deltas_Y = Y - Y.T

distancias_ao_quadrado = deltas_X**2 + deltas_Y**2

distancias = np.sqrt(distancias_ao_quadrado)

print("Matriz de Distâncias 5x5")
print(distancias.round(2))

Pontos Originais (P) shape: (5, 2)
[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]
 [0.7611397  0.78606431]
 [0.12811363 0.45038594]]

Matriz de Distâncias 5x5
[[0.   0.27 0.87 0.35 0.65]
 [0.27 0.   0.81 0.13 0.77]
 [0.87 0.81 0.   0.69 0.53]
 [0.35 0.13 0.69 0.   0.72]
 [0.65 0.77 0.53 0.72 0.  ]]


### 35. Covariância e correlação  _(médio)_

Simule uma matriz 1000×3 de N(0,1) e compute `cov` (colunas como variáveis) e `corrcoef`.

In [191]:
rng = np.random.default_rng(42)

A = rng.standard_normal(size=(1000, 3))

cov_matrix = np.cov(A.T)

print("Matriz de Covariância (3x3)")
print(cov_matrix.round(4))

corr_matrix = np.corrcoef(A.T)

print("Matriz de Correlação (3x3)")
print(corr_matrix.round(4))

Matriz de Covariância (3x3)
[[ 1.0281  0.0034 -0.0303]
 [ 0.0034  0.9969  0.0635]
 [-0.0303  0.0635  1.0227]]
Matriz de Correlação (3x3)
[[ 1.      0.0034 -0.0295]
 [ 0.0034  1.      0.0629]
 [-0.0295  0.0629  1.    ]]


### 36. One-hot encoding  _(médio)_

Converta os rótulos `y = [2,0,1,2]` em codificação one-hot usando apenas operações NumPy.


In [193]:
y = np.array([2, 0, 1, 2])

num_classes = np.max(y) + 1

modelo = np.eye(num_classes, dtype=int)
one_hot = modelo[y]

print("Matriz")
print(modelo)
print("\nResultado One-Hot (modelo[y]):")
print(one_hot)

Matriz
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Resultado One-Hot (modelo[y]):
[[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


## Difíceis (6)

### 37. k-means 2D (NumPy puro)  _(difícil)_

Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios, faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.

In [194]:
rng = np.random.default_rng(42)
K = 3
M = 20
D = 2
N_ITER = 5


pontos = rng.random(size=(M, D)) * 10

indices_iniciais = rng.choice(M, K, replace=False)
centroides = pontos[indices_iniciais]

print(f"Temos {M} pontos.")
print(f"Centróides Iniciais (aleatórios):\n{centroides.round(2)}")
print("\n--- Começando as Iterações ---")

for i in range(N_ITER):
    print(f"Iteração {i+1}/{N_ITER}...")

    distancias = np.zeros((M, K))


    for k in range(K):
        centroide_k = centroides[k]

        dist_sq = ((pontos - centroide_k)**2).sum(axis=1)

        distancias[:, k] = np.sqrt(dist_sq)

    labels = np.argmin(distancias, axis=1)

    for k in range(K):
        pontos_do_cluster = pontos[labels == k]

        if len(pontos_do_cluster) > 0:
            centroides[k] = pontos_do_cluster.mean(axis=0)

print("\n--- K-Means Concluído ---")
print(f"Centróides Finais:\n{centroides.round(2)}")
print(f"\nAtribuição final (qual cluster cada ponto pertence):")
print(labels)

Temos 20 pontos.
Centróides Iniciais (aleatórios):
[[3.26 3.7 ]
 [5.55 0.64]
 [7.61 7.86]]

--- Começando as Iterações ---
Iteração 1/5...
Iteração 2/5...
Iteração 3/5...
Iteração 4/5...
Iteração 5/5...

--- K-Means Concluído ---
Centróides Finais:
[[2.04 6.5 ]
 [6.06 2.16]
 [8.01 8.  ]]

Atribuição final (qual cluster cada ponto pertence):
[1 2 0 2 0 0 2 1 1 2 1 2 1 1 0 2 0 1 0 0]



### 38. PCA básica (autovetores)  _(difícil)_

Implemente PCA 2D→1D: centralize `X` (N×2), calcule covariância, autovetores, projete em 1D e reconstrua aproximado.


### 39. Convolução 2D (im2col)  _(difícil)_

Implemente convolução 2D 'valid' de uma imagem `I` por um kernel `K` usando `sliding_window_view` para gerar blocos e multiplicação matricial.

### 40. Sistemas lineares e resíduo  _(difícil)_

Gere uma matriz A (100×100) bem-condicionada, um vetor b e resolva `Ax=b` com `np.linalg.solve`. Compute o resíduo relativo `||Ax−b||/||b||` e `cond(A)`.

### 41. Regressão linear (OLS) com NumPy  _(difícil)_

Dado `X` (N×d) e `y`, calcule os coeficientes OLS usando `np.linalg.lstsq` e avalie RMSE no treino.

### 42. Rolling window 2D com strides  _(difícil)_

Usando `sliding_window_view`, compute a média local 3×3 de uma imagem 2D sem laços explícitos.