<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-danilbalistero/blob/main/TarefaPratica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fáceis
### 1. Vetor de zeros
**Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.**

In [14]:
import numpy as np

a1D = np.zeros(10)
print(a1D)
print(a1D.dtype)
print(a1D.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


### 2. Vetor de uns  _(fácil)_

**Crie um array 1D com 10 uns e transforme-o em float64.**

In [15]:
a1D = np.ones(10)
print(a1D)
print(a1D.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64



### 3. Sequência 0–9  _(fácil)_

Crie um array com os inteiros de 0 a 9 (inclusive).

In [17]:
a1D = np.arange(10)
print(a1D)

[0 1 2 3 4 5 6 7 8 9]



### 4. Matriz 3×3 com 0…8  _(fácil)_

Crie um array 3×3 com os valores 0…8 (reshape).

In [22]:
a2D = np.arange(9).reshape(3, 3)
print(a2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
